<?php

return [
    'definitions' => [
        'basic' => [
            'label' => 'Basic',
            'price_monthly' => 29,
            'price_annual_monthly' => 24,
            'features' => [
                'inventory_tracking' => true,
                'stock_alerts' => true,
                'pos_system' => false,
                'supplier_management' => false,
                'customer_management' => false,
                'basic_reports' => false,
                'advanced_analytics' => false,
                'data_export' => false,
                'api_access' => false,
                'custom_branding' => false,
                'priority_support' => false,
                'sms_notifications' => false,
                'batch_operations' => false,
                'export_csv' => false,
                'export_excel' => false,
                'export_pdf' => false,
            ],
            'limits' => [
                'max_branches' => 1,
                'max_users' => 1,
                'max_products' => 100,
                'max_monthly_transactions' => 3000,
                'max_api_calls_per_month' => 0,
                'max_storage_mb' => 1024,
                'data_retention_months' => 6,
            ],
        ],

        'standard' => [
            'label' => 'Standard',
            'price_monthly' => 79,
            'price_annual_monthly' => 66,
            'features' => [
                'inventory_tracking' => true,
                'stock_alerts' => true,
                'pos_system' => true,
                'supplier_management' => true,
                'customer_management' => true,
                'basic_reports' => true,
                'data_export' => true,
                'export_csv' => true,
                'export_excel' => false,
                'export_pdf' => false,
                'api_access' => false,
                'advanced_analytics' => false,
                'custom_branding' => false,
                'sms_notifications' => false,
                'priority_support' => false,
                'batch_operations' => false,
            ],
            'limits' => [
                'max_branches' => 1,
                'max_users' => 3,
                'max_products' => 999999,
                'max_monthly_transactions' => 15000,
                'max_api_calls_per_month' => 0,
                'max_storage_mb' => 5120,
                'data_retention_months' => 24,
            ],
        ],

        'premium' => [
            'label' => 'Premium',
            'price_monthly' => 149,
            'price_annual_monthly' => 125,
            'features' => [
                'inventory_tracking' => true,
                'stock_alerts' => true,
                'pos_system' => true,
                'supplier_management' => true,
                'customer_management' => true,
                'basic_reports' => true,
                'advanced_analytics' => true,
                'data_export' => true,
                'export_csv' => true,
                'export_excel' => true,
                'export_pdf' => true,
                'api_access' => true,
                'batch_operations' => true,
                'custom_branding' => true,
                'priority_support' => true,
                'sms_notifications' => true,
            ],
            'limits' => [
                'max_branches' => 5,
                'max_users' => null,
                'max_products' => 999999,
                'max_monthly_transactions' => 60000,
                'max_api_calls_per_month' => 100000,
                'max_storage_mb' => 20480,
                'data_retention_months' => 60,
            ],
        ],

        // Keep enterprise for backward compatibility in existing validation/routes.
        'enterprise' => [
            'label' => 'Enterprise',
            'price_monthly' => null,
            'price_annual_monthly' => null,
            'features' => [
                'inventory_tracking' => true,
                'stock_alerts' => true,
                'pos_system' => true,
                'supplier_management' => true,
                'customer_management' => true,
                'basic_reports' => true,
                'advanced_analytics' => true,
                'data_export' => true,
                'api_access' => true,
                'webhooks' => true,
                'custom_branding' => true,
                'approval_workflows' => true,
                'priority_support' => true,
                'batch_tracking' => true,
                'wastage_tracking' => true,
                'expiry_monitoring' => true,
                'dedicated_database' => true,
                'custom_integrations' => true,
                'sla_support' => true,
            ],
            'limits' => [
                'max_branches' => 999,
                'max_users' => 999,
                'max_products' => 999999,
                'max_monthly_transactions' => 999999,
                'max_api_calls_per_month' => 999999,
                'max_storage_mb' => 102400,
                'data_retention_months' => 120,
            ],
        ],
    ],
];
